Repository AmandaStromdahl/DD2480_CodeComplexity_Coverage, pull requests merged in 2022-02, with the labels that each got.

#24 Analysis of the functions #4 #5 #23
  complex_functions/cycle_sort.py
  complex_functions/interpolation_search.py
  complex_functions/spiral_print.py
  report.md
Labels: enhancement

#27 doc, feat: added description of deutsch_jozsa algorithm #2
  complex_functions/deutsch_jozsa.py
  report.md
Labels: documentation

#28 Strassen
  complex_functions/strassen.py
  report.md
Labels: documentation

#31 feat: issue #30 added the coverage percentage
  coverage_analysis/data_structure/coverage_tool.py
Labels: enhancement

#33 Coverage tool improved
  .gitignore
  coverage_analysis/coverage_tests/__init__.py
  coverage_analysis/coverage_tests/cycle_sort_test.py
  coverage_analysis/coverage_tests/spiral_print_test.py
  coverage_analysis/data_structure/coverage_tool.py
  coverage_analysis/functions_analysed/__init__.py
  coverage_analysis/functions_analysed/cycle_sort_coverage.py
  coverage_analysis/functions_analysed/spiral_print_coverage.py
Labels: enhancement

#42 feat: issue #41 add a test section for coverage.py
  complex_functions/__init__.py
  complex_functions/spiral_print.py
  complex_functions/tests/.coverage
  complex_functions/tests/cycle_sort_test.py
  complex_functions/tests/run.sh
  complex_functions/tests/spiral_print_test.py
Labels: enhancement

#44 Refactored cycle_sort()
  refactored_functions/cycle_sort.py
  report.md
Labels: documentation, enhancement

#45 Add: Added a secondary counting of the cyclomatic complexity to some …
  report.md
Labels: documentation

#57 feat: added strassen_test and deutsch_jozsa_test to /tests #55
  complex_functions/strassen.py
  complex_functions/tests/deutsch_jozsa_test.py
  complex_functions/tests/strassen_test.py
Labels: enhancement

#58 Onboarding
  report.md
Labels: documentation

#54 Feat: Simulated Annealing, analysis and refactoring
  complex_functions/SearchProblem.py
  complex_functions/simulated_annealing.py
  refactored_functions/SearchProblem.py
  refactored_functions/simulated_annealing.py
  report.md
Labels: enhancement

#63 Add: Added an analysis and statemnt of how to refactor the function h…
  complex_functions/rgb_hsv_conversion.py
  report.md
Labels: enhancement

#68 Feat: Hsv to rgb tests
  complex_functions/tests/.coverage
  complex_functions/tests/hsv_to_rgb_test.py
Labels: enhancement

#74 doc: issue #73 added the documentation about our tool
  report.md
Labels: documentation

#78 fix: issue #77 fixed type errors
  complex_functions/rgb_hsv_conversion.py
  complex_functions/tests/.coverage
Labels: bug
